import type { I18nText, SchoolImageFile } from "@/data/schoolTypes";
import LocalizedInput from "@/components/admin/LocalizedInput";

export type EditableImageBlock = { src?: string; alt?: I18nText; caption?: I18nText; width?: number; height?: number; files?: SchoolImageFile[] };
const inputClass = "w-full border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950 dark:text-white";

export default function ImageEditor<T extends EditableImageBlock>({ block, onChange }: { block: T; onChange: (block: T) => void }) {
  const setFiles = (files: SchoolImageFile[]) => onChange({ ...block, files, src: undefined, alt: undefined, caption: undefined, width: undefined, height: undefined } as T);
  if (block.files?.length) {
    return <div className="space-y-5">{block.files.map((file, index) => <fieldset key={index} className="space-y-4 border border-slate-200 p-4 dark:border-slate-800"><legend className="px-2 text-xs font-semibold text-slate-500">IMAGE {index + 1}</legend><LocalizedInput label="タブ名" value={file.tabLabel} onChange={(tabLabel) => setFiles(block.files!.map((item, i) => i === index ? { ...item, tabLabel } : item))} allowEmpty /><label className="block text-sm">画像URL *<input value={file.src} onChange={(event) => setFiles(block.files!.map((item, i) => i === index ? { ...item, src: event.target.value } : item))} className={`${inputClass} mt-1`} /></label><LocalizedInput label="Alt" value={file.alt} onChange={(alt) => setFiles(block.files!.map((item, i) => i === index ? { ...item, alt } : item))} allowEmpty /><LocalizedInput label="Caption" value={file.caption} onChange={(caption) => setFiles(block.files!.map((item, i) => i === index ? { ...item, caption } : item))} allowEmpty /><Dimensions file={file} onChange={(next) => setFiles(block.files!.map((item, i) => i === index ? next : item))} /><button type="button" disabled={block.files!.length === 1} onClick={() => setFiles(block.files!.filter((_, i) => i !== index))} className="text-xs text-red-600 disabled:opacity-30">画像を削除</button></fieldset>)}<div className="flex gap-3"><button type="button" onClick={() => setFiles([...block.files!, { src: "", alt: { ja: "", en: "" } }])} className="secondary-link">画像を追加</button><button type="button" onClick={() => { const first = block.files![0]; onChange({ ...block, files: undefined, ...first } as T); }} className="text-xs text-slate-500">単一画像に戻す</button></div></div>;
  }
  const file: SchoolImageFile = { src: block.src ?? "", alt: block.alt, caption: block.caption, width: block.width, height: block.height };
  return <div className="space-y-4"><label className="block text-sm">画像URL *<input value={block.src ?? ""} onChange={(event) => onChange({ ...block, src: event.target.value })} placeholder="/images/..." className={`${inputClass} mt-1`} /></label><LocalizedInput label="Alt" value={block.alt} onChange={(alt) => onChange({ ...block, alt })} allowEmpty /><LocalizedInput label="Caption" value={block.caption} onChange={(caption) => onChange({ ...block, caption })} allowEmpty /><Dimensions file={file} onChange={(next) => onChange({ ...block, width: next.width, height: next.height } as T)} /><button type="button" onClick={() => setFiles([{ ...file, tabLabel: { ja: "画像 1", en: "Image 1" } }])} className="secondary-link">複数画像にする</button></div>;
}

function Dimensions({ file, onChange }: { file: SchoolImageFile; onChange: (file: SchoolImageFile) => void }) {
  return <div className="grid grid-cols-2 gap-3"><label className="text-xs text-slate-500">Width<input type="number" min="1" value={file.width ?? ""} onChange={(event) => onChange({ ...file, width: event.target.value ? Number(event.target.value) : undefined })} className={`${inputClass} mt-1`} /></label><label className="text-xs text-slate-500">Height<input type="number" min="1" value={file.height ?? ""} onChange={(event) => onChange({ ...file, height: event.target.value ? Number(event.target.value) : undefined })} className={`${inputClass} mt-1`} /></label></div>;
}
